#if !canImport(ObjectiveC)
import XCTest

extension HwpEquationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HwpEquationTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HwpEquationTests.__allTests__HwpEquationTests),
    ]
}
#endif
